### ISSUE TITLE
Hide selectors and disable add button

### ISSUE THREAD

**Issue by yeyeto2788** [yeyeto2788/Things-Organizer#20]
Once a user is registered and goes straight into the `Add new Thing` page there is no `Categories` or `Storage` to select from (Red selection on image below).

<img width="960" alt="add_thing_annotations" src="https://user-images.githubusercontent.com/6363686/56960421-01e7c400-6b51-11e9-8a6e-f6b60050d446.png">

**Possible fixes:**
1. Launch a pop-up telling the user to go and add the missing items (Categories or Storage).
2. Disable the add button and hide the `Category` and `Storage` selectors and add a button to redirect the user to those pages.

**Notes:**
Take into account that if no Category is added and there is at least one Storage the message should point the user to add at least a Category to proceed. The proccess will be the same in the other way around.

**Comment by yeyeto2788** [comment]
@gangsthub can you please take a look into this get you get a chance?

Regards.

**Comment by paulmelero** [comment]
> @gangsthub can you please take a look into this get you get a chance?

Hi, maybe you wanted to ping another person? 🤔
